# Generated by Django 4.1.3 on 2022-11-24 02:10

from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCommissionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_week', models.PositiveIntegerField(choices=[(1, 'Segunda-feira'), (2, 'Terça-feira'), (3, 'Quarta-feira'), (4, 'Quinta-feira'), (5, 'Sexta-feira'), (6, 'Sábado'), (7, 'Domingo')], verbose_name='Dia da semana')),
                ('min_percentage', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[product.models.validate_commission_percentage], verbose_name='Porcentagem mínima')),
                ('max_percentage', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[product.models.validate_commission_percentage], verbose_name='Porcentagem máxima')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'verbose_name': 'agenda de comissão do produto',
                'verbose_name_plural': 'agendas de comissão dos produtos',
            },
        ),
    ]
