# Generated by Django 4.1.3 on 2022-11-25 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productcommissionschedule'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productcommissionschedule',
            unique_together={('day_week', 'product')},
        ),
    ]
