# Generated by Django 4.1.3 on 2022-11-25 01:25

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_productcommissionschedule_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcommissionschedule',
            name='max_percentage',
            field=models.DecimalField(decimal_places=1, default=10, max_digits=3, null=True, validators=[product.models.validate_commission_percentage], verbose_name='Porcentagem máxima'),
        ),
        migrations.AlterField(
            model_name='productcommissionschedule',
            name='min_percentage',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, validators=[product.models.validate_commission_percentage], verbose_name='Porcentagem mínima'),
        ),
    ]
