# Generated by Django 4.1.3 on 2022-11-24 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='register_datetime',
            field=models.DateTimeField(verbose_name='Data de registro'),
        ),
    ]
