# Generated by Django 4.1.3 on 2022-11-24 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_alter_sale_register_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Total'),
        ),
        migrations.AddField(
            model_name='saleproduct',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Total'),
        ),
    ]
