# Generated by Django 4.1.3 on 2022-11-24 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_sale_total_saleproduct_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='register_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de registro'),
        ),
    ]
